export const START_LOADING = "cafe/START_LOADING";
export const END_LOADING = "cafe/END_LOADING";
export const FETCH_CAFES = "FETCH_CAFES";
export const FETCH_CAFES_BY_PAGES = "FETCH_CAFES_BY_PAGES";
export const FETCH_CAFE = "FETCH_CAFE";
export const CREATE_CAFE = "CREATE_CAFE";
export const UPDATE_CAFE = "UPDATE_CAFE";
export const DELETE_CAFE = "DELETE_CAFE";

export const FETCH_CAFE_REVIEWS = "FETCH_CAFE_REVIEWS";
export const CREATE_CAFE_REVIEW = "CREATE_CAFE_REVIEW";
export const UPDATE_CAFE_REVIEW = "UPDATE_CAFE_REVIEW";
export const DELETE_CAFE_REVIEW = "DELETE_CAFE_REVIEW";
