export const START_LOADING = "courses/START_LOADING";
export const END_LOADING = "courses/END_LOADING";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_BY_SEARCH = "FETCH_COURSES_BY_SEARCH";
export const FETCH_COURSE = "FETCH_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";

export const FETCH_COURSE_REVIEWS = "FETCH_COURSE_REVIEWS";
export const CREATE_COURSE_REVIEW = "CREATE_COURSE_REVIEW";
export const UPDATE_COURSE_REVIEW = "UPDATE_COURSE_REVIEW";
export const DELETE_COURSE_REVIEW = "DELETE_COURSE_REVIEW";
