export const START_LOADING = "foodNomination/START_LOADING";
export const END_LOADING = "foodNomination/END_LOADING";
export const FETCH_FOOD_NOMINATIONS = "FETCH_FOOD_NOMINATIONS";
export const FETCH_FOOD_NOMINATION = "FETCH_FOOD_NOMINATION";
export const CREATE_FOOD_NOMINATION = "CREATE_FOOD_NOMINATION";
export const DELETE_FOOD_NOMINATION = "DELETE_FOOD_NOMINATION";
export const APPROVE_FOOD_NOMINATION = "APPROVE_FOOD_NOMINATION";
export const DECLINE_FOOD_NOMINATION = "DECLINE_FOOD_NOMINATION";
